/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class adminpassword extends javax.swing.JFrame {

    /**
     *
     */
    public adminpassword() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("ADMIN PASSWORD");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbladminpassword = new javax.swing.JLabel();
        txtadminpassword = new javax.swing.JPasswordField();
        btnEnter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbladminpassword.setText("ENTER ADMIN PASSWORD");

        btnEnter.setText("ENTER");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbladminpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtadminpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btnEnter)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbladminpassword)
                .addGap(43, 43, 43)
                .addComponent(txtadminpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnEnter)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed

    
    String enteredPassword =txtadminpassword.getText();
    String dbPassword = null;
    
    Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    String admin = "ADMINISTRATOR";

    // 1. SQL Query to fetch the password for 'Nico Jack'
    // NOTE: Replace 'FirstName' with the column name used for names if different.
    String sql = "SELECT password FROM persons WHERE ROLE = ?"; 

    try {
        // Load Driver and Establish Connection
        Class.forName("com.mysql.cj.jdbc.Driver"); 
        //conn = DriverManager.getConnection( "jdbc:mysql://localhost:3306/hostel_management_system", "root", "");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel_management_system","root", "mark24");
        // Prepare Statement
        pstmt = conn.prepareStatement(sql);
       // pstmt.setString(1, enteredPassword);
        pstmt.setString(1, admin);
        // Execute Query
        rs = pstmt.executeQuery();
        
        if (rs.next()) {
            // Get the password from the database result set
            dbPassword = rs.getString("password"); 
        }

    } catch (ClassNotFoundException e) {
        JOptionPane.showMessageDialog(this, "JDBC Driver not found.", "DB Error", JOptionPane.ERROR_MESSAGE);
        return; // Stop if connection fails
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database Error during login: " + e.getMessage(), "DB Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
        return; // Stop if query fails
    } finally {
        // Close resources
        try {
            if (rs != null) rs.close();
            if (pstmt != null) pstmt.close();
            if (conn != null) conn.close();
        } catch (SQLException e) {
            System.err.println("Error closing resources: " + e.getMessage());
        }
    }
    
    // 2. Perform Password Validation (Outside of the try/catch block)
    
    // Check if a password was found AND if it matches the entered password
    if (dbPassword != null && enteredPassword.equals(dbPassword)) {
        
        // --- Successful Login ---
        JOptionPane.showMessageDialog(this, " Login Successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
       
        // Close the current password entry window
        
        this.dispose();
        AdminForm.Main();
        

    } else {
        // --- Failed Login ---
        JOptionPane.showMessageDialog(this, "Incorrect Password ", "Login Failed", JOptionPane.ERROR_MESSAGE);
        
        // Clear the password field
        txtadminpassword.setText("");
    
}

    }//GEN-LAST:event_btnEnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void adminPassword() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminpassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnter;
    private javax.swing.JLabel lbladminpassword;
    private javax.swing.JPasswordField txtadminpassword;
    // End of variables declaration//GEN-END:variables
}
