/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
import java.text.SimpleDateFormat; //
import java.util.Date;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import java.awt.Desktop;
import java.io.File;
public class AdminForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminForm
     */
    public AdminForm() {
        initComponents();
        setLocationRelativeTo(null);
        studentPanel.setVisible(true);
        staffPanel.setVisible(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staffPanel = new javax.swing.JPanel();
        lblstfName = new javax.swing.JLabel();
        lblEmployeeID = new javax.swing.JLabel();
        lbldateofhire = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblSalary = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblDepartmentID = new javax.swing.JLabel();
        lblStfpassword = new javax.swing.JLabel();
        txtemployeeID = new javax.swing.JTextField();
        txtStfName = new javax.swing.JTextField();
        txtRole = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        txtDepartmentID = new javax.swing.JTextField();
        txtStfpassword = new javax.swing.JTextField();
        statusBox = new javax.swing.JComboBox<>();
        txtdateofhire = new com.toedter.calendar.JDateChooser();
        AddStaff = new javax.swing.JButton();
        lblRegID = new javax.swing.JLabel();
        txtstfRegID = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        studentPanel = new javax.swing.JPanel();
        lblStdname = new javax.swing.JLabel();
        lblyear = new javax.swing.JLabel();
        lblcourse = new javax.swing.JLabel();
        lblemergencyContact = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblemergencyRelation = new javax.swing.JLabel();
        txtstdName = new javax.swing.JTextField();
        txtcourse = new javax.swing.JTextField();
        txtemergencyContact = new javax.swing.JTextField();
        txtemergencyName = new javax.swing.JTextField();
        txtemergencyRelation = new javax.swing.JTextField();
        lblemergencyName = new javax.swing.JLabel();
        txtDateOfEnrollment = new com.toedter.calendar.JDateChooser();
        lblstdpassword = new javax.swing.JLabel();
        txtstdpassword = new javax.swing.JTextField();
        AddStudent = new javax.swing.JButton();
        lblRegID1 = new javax.swing.JLabel();
        txtstdRegID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        complaintsMenu = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 255));

        staffPanel.setBackground(new java.awt.Color(0, 102, 255));
        staffPanel.setForeground(new java.awt.Color(255, 255, 255));

        lblstfName.setText("NAME");

        lblEmployeeID.setText("EMPLOYEE ID");

        lbldateofhire.setText("DATE OF HIRE");

        lblRole.setText("ROLE");

        lblSalary.setText("SALARY");

        lblStatus.setText(" STATUS");

        lblDepartmentID.setText("DEPARTMENT ID");

        lblStfpassword.setText("CREATE PASSWORD");

        txtStfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStfNameActionPerformed(evt);
            }
        });

        txtRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoleActionPerformed(evt);
            }
        });

        txtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaryActionPerformed(evt);
            }
        });

        txtStfpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStfpasswordActionPerformed(evt);
            }
        });

        statusBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVE", "INACTIVE", "FIRED" }));

        txtdateofhire.setDateFormatString("yyyy-MM-dd");

        AddStaff.setText("ADD STAFF MEMBER");
        AddStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStaffActionPerformed(evt);
            }
        });

        lblRegID.setText("REG ID");

        txtstfRegID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstfRegIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout staffPanelLayout = new javax.swing.GroupLayout(staffPanel);
        staffPanel.setLayout(staffPanelLayout);
        staffPanelLayout.setHorizontalGroup(
            staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus)
                    .addComponent(lblStfpassword)
                    .addComponent(lblRole)
                    .addComponent(lblstfName)
                    .addComponent(lblEmployeeID)
                    .addComponent(lbldateofhire)
                    .addComponent(txtdateofhire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSalary)
                    .addComponent(statusBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDepartmentID)
                    .addComponent(AddStaff)
                    .addComponent(lblRegID)
                    .addComponent(txtstfRegID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStfName, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(txtemployeeID)
                    .addComponent(txtRole)
                    .addComponent(txtSalary)
                    .addComponent(txtDepartmentID)
                    .addComponent(txtStfpassword))
                .addGap(45, 45, 45))
        );
        staffPanelLayout.setVerticalGroup(
            staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblRegID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtstfRegID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblstfName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmployeeID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtemployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbldateofhire)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdateofhire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(lblRole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSalary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDepartmentID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDepartmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStfpassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStfpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddStaff)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        studentPanel.setBackground(new java.awt.Color(0, 102, 255));

        lblStdname.setText("NAME");

        lblyear.setText("DATE OF ENROLLMENT");

        lblcourse.setText("COURSE");

        lblemergencyContact.setText("EMERGENCY CONTACT PHONE");

        lblemergencyRelation.setText("EMERGENCY CONTACT RELATION");

        txtcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcourseActionPerformed(evt);
            }
        });

        txtemergencyContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemergencyContactActionPerformed(evt);
            }
        });

        lblemergencyName.setText("ENERGENCY CONTACT NAME");

        txtDateOfEnrollment.setDateFormatString("yyyy-MM-dd");

        lblstdpassword.setText("CREATE PASSWORD");

        AddStudent.setText("ADD STUDENT");
        AddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentActionPerformed(evt);
            }
        });

        lblRegID1.setText("REG ID");

        jButton1.setText("ASSIGN ROOM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentPanelLayout = new javax.swing.GroupLayout(studentPanel);
        studentPanel.setLayout(studentPanelLayout);
        studentPanelLayout.setHorizontalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStdname)
                    .addComponent(lblRegID1)
                    .addGroup(studentPanelLayout.createSequentialGroup()
                        .addComponent(AddStudent)
                        .addGap(33, 33, 33)
                        .addComponent(jButton1))
                    .addGroup(studentPanelLayout.createSequentialGroup()
                        .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtstdRegID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblemergencyRelation)
                            .addComponent(lblcourse)
                            .addComponent(lblyear)
                            .addComponent(lblemergencyName)
                            .addComponent(lblemergencyContact)
                            .addComponent(txtDateOfEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblstdpassword)
                            .addComponent(txtstdName, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(txtemergencyRelation)
                            .addComponent(txtemergencyContact)
                            .addComponent(txtemergencyName)
                            .addComponent(txtcourse)
                            .addComponent(txtstdpassword))
                        .addGap(140, 140, 140)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        studentPanelLayout.setVerticalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addComponent(lblRegID1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtstdRegID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblStdname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtstdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblcourse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblyear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDateOfEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblemergencyName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtemergencyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblemergencyContact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtemergencyContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblemergencyRelation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtemergencyRelation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblstdpassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtstdpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddStudent)
                    .addComponent(jButton1))
                .addGap(138, 138, 138))
        );

        jMenu3.setText("ROOMS");

        jMenuItem2.setText("ADD ROOMS");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("PAYMENTS");

        jMenuItem4.setText("ADD PAYMENT DETAILS");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("MORE");

        complaintsMenu.setText("STAFF COMPLAINTS");
        complaintsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complaintsMenuActionPerformed(evt);
            }
        });
        jMenu1.add(complaintsMenu);

        jMenuItem1.setText("VIEW REGISTERED STAFF");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("VIEW REGISTERED STUDENTS");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(staffPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentActionPerformed
        // 1. Retrieve Data from Form Fields
        // txtstdRegID.getText().trim();

        String personID = txtstdRegID.getText().trim();
        String fullName = txtstdName.getText().trim();
        String courseOfStudy = txtcourse.getText().trim();
        String emergencyName = txtemergencyName.getText().trim();
        String emergencyPhone = txtemergencyContact.getText().trim();
        String emergencyRelation = txtemergencyRelation.getText().trim();
        String password = txtstdpassword.getText(); // Get password as a String
        String enrollmentDateStr = null;
        int currentYearOfStudy = 1; // Defaulting to 1 for a new student

        // If using a JDateChooser (common component):
        try {
            Date date = txtDateOfEnrollment.getDate(); // Assuming dateEnrollment is a JDateChooser
            if (date != null) {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                enrollmentDateStr = sdf.format(date);
            }
        } catch (Exception e) {
            // Handle case where date component is missing or date is invalid
            enrollmentDateStr = null;
        }

        // 2. Basic Validation
        if (personID.isEmpty()|| fullName.isEmpty() || courseOfStudy.isEmpty() || password.isEmpty() || enrollmentDateStr == null) {
            JOptionPane.showMessageDialog(this, "Please ensure student ID Name, Course, Enrollment Date, and Password are filled.", "Input Missing", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int personintID;
        try {
            personintID = Integer.parseInt(personID); // <--- NEW: Convert ID to integer
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Person ID must be a valid whole number.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Database Insertion Setup
        Connection conn = null;
        PreparedStatement pstmt = null;

        // Use a parameterized query for security (avoids SQL Injection)
        String sql = "INSERT INTO students (StudentID, PersonID ,Fullname, CourseOfStudy, EnrollmentDate, CurrentYearOfStudy, "
        + "EmergencyContactName, EmergencyContactPhone, EmergencyContactRelation, password) "
        + "VALUES (?,?, ?, ?, ?, ?, ?, ?, ?,?)";

        try {
            // a. Connect
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel_management_system","root", "mark24");
            pstmt = conn.prepareStatement(sql);

            // b. Set Parameters (Mapping in order of the SQL statement)
            pstmt.setInt(1, personintID);
            pstmt.setInt(2, personintID);
            pstmt.setString(3, fullName);
            pstmt.setString(4, courseOfStudy);
            pstmt.setString(5, enrollmentDateStr); // Date format: YYYY-MM-DD
            pstmt.setInt(6, currentYearOfStudy);
            pstmt.setString(7, emergencyName);
            pstmt.setString(8, emergencyPhone);
            pstmt.setString(9, emergencyRelation);
            pstmt.setString(10, password); // Storing the plain password as requested

            // c. Execute
            int rowsAffected = pstmt.executeUpdate();

            // d. Feedback and Clear Form
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Student record added successfully! ✅", "Success", JOptionPane.INFORMATION_MESSAGE);

                // Clear fields (Optional but recommended)
                txtstdName.setText("");
                txtcourse.setText("");
                // dateEnrollment.setDate(null);
                txtemergencyName.setText("");
                txtemergencyContact.setText("");
                txtemergencyRelation.setText("");
                txtstdpassword.setText("");

            } else {
                JOptionPane.showMessageDialog(this, "Failed to add student record.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException ex) {
            // e. Handle Exceptions
            JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "SQL Exception", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } finally {
            // f. Close Resources
            try {
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                System.err.println("Error closing resources: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_AddStudentActionPerformed

    private void txtemergencyContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemergencyContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemergencyContactActionPerformed

    private void txtcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcourseActionPerformed

    private void txtstfRegIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstfRegIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstfRegIDActionPerformed

    private void AddStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStaffActionPerformed
        // 1. Retrieve and Validate Data
        String regIDStr = txtstfRegID.getText().trim();
        String fullName = txtStfName.getText().trim();
        String employeeID = txtemployeeID.getText().trim();
        String role = txtRole.getText().trim();
        String salaryStr = txtSalary.getText().trim();
        String status = (String) statusBox.getSelectedItem(); // Assuming JComboBox named cmbStatus
        String deptIDStr = txtDepartmentID.getText().trim();
        String password = txtStfpassword.getText();
        String dateOfHireStr = null;

        // --- Date Handling (Assuming JDateChooser named dateHire) ---
        try {
            Date date = txtdateofhire.getDate();
            if (date != null) {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                dateOfHireStr = sdf.format(date);
            }
        } catch (Exception e) {
            dateOfHireStr = null;
        }
        // ------------------------------------------------------------

        // 2. Comprehensive Validation and Type Conversion
        if (regIDStr.isEmpty() || fullName.isEmpty() || employeeID.isEmpty() ||
            role.isEmpty() || salaryStr.isEmpty() || deptIDStr.isEmpty() ||
            password.isEmpty() || dateOfHireStr == null)
        {
            JOptionPane.showMessageDialog(this, "Please fill all required fields.", "Input Missing", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int regID, deptID;
        double salary;

        try {
            regID = Integer.parseInt(regIDStr);
            deptID = Integer.parseInt(deptIDStr);
            salary = Double.parseDouble(salaryStr); // Use Double for potential decimal salaries
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID, Salary, and Dept ID must be valid numbers.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Database Insertion Setup
        Connection conn = null;
        PreparedStatement pstmt = null;

        // Assuming your Staff table is named 'Staff' or 'Employee'
        String sql = "INSERT INTO Staff (PersonID, FullName, EmployeeID, DateOfHire, JobTitle, Salary, EmploymentStatus, DepartmentID, password) "
        + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

        try {
            // a. Connect
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel_management_system","root", "mark24");
            pstmt = conn.prepareStatement(sql);

            // b. Set Parameters (9 fields in total)
            pstmt.setInt(1, regID);
            pstmt.setString(2, fullName);
            pstmt.setString(3, employeeID);
            pstmt.setString(4, dateOfHireStr);
            pstmt.setString(5, role);
            pstmt.setDouble(6, salary);
            pstmt.setString(7, status);
            pstmt.setInt(8, deptID);
            pstmt.setString(9, password);

            // c. Execute
            int rowsAffected = pstmt.executeUpdate();

            // d. Feedback and Clear Form
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Staff member added successfully! ✅", "Success", JOptionPane.INFORMATION_MESSAGE);

                // Clear fields (Optional)
                txtstfRegID.setText("");
                txtStfName.setText("");
                txtemployeeID.setText("");
                // dateHire.setDate(null); // Clear the JDateChooser
                txtRole.setText("");
                txtSalary.setText("");
                // cmbStatus.setSelectedIndex(0); // Reset dropdown
                txtDepartmentID.setText("");
                txtStfpassword.setText("");

            } else {
                JOptionPane.showMessageDialog(this, "Failed to add staff member.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException ex) {
            // e. Handle Exceptions
            JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "SQL Exception", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } finally {
            // f. Close Resources
            try {
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                System.err.println("Error closing resources: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_AddStaffActionPerformed

    private void txtStfpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStfpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStfpasswordActionPerformed

    private void txtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaryActionPerformed

    private void txtRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoleActionPerformed

    private void txtStfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStfNameActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Payments.Main();
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AssignRoom.Main();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        AddRooms.Main();
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void complaintsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complaintsMenuActionPerformed
        ViewComplaints.Main();
    }//GEN-LAST:event_complaintsMenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    Document document = new Document();
    String filePath = "StaffReport.pdf"; // Output file name

    // SQL to fetch Staff data: Filtering by ROLE
    String sql = "SELECT PersonID, FirstName, DateOfBirth, Gender, Email, PhoneNumber, City, ROLE "
               + "FROM persons WHERE ROLE IN ('STAFF') ORDER BY PersonID";

    try {
        // 1. Database Connection
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel_management_system","root", "");
        pstmt = conn.prepareStatement(sql);
        rs = pstmt.executeQuery();

        // 2. iText Setup
        PdfWriter.getInstance(document, new FileOutputStream(filePath));
        document.open();

        // 3. Add Title and Header (8 columns)
         Paragraph title = new Paragraph("MILE 6 HOSTEL");
        title.setAlignment(Element.ALIGN_CENTER);
        title.setSpacingAfter(20);
        title.setFont(new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 16, com.itextpdf.text.Font.BOLD));
        document.add(title);
        document.add(new Paragraph("\n\nRegistered Staff Report\n\n", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18)));
        PdfPTable table = new PdfPTable(8); 
        table.setWidthPercentage(100);
        
        // Headers
        table.addCell("ID"); table.addCell("Name"); table.addCell("DOB");
        table.addCell("Gender"); table.addCell("Email"); table.addCell("Phone");
        table.addCell("City"); table.addCell("Role");

        // 4. Populate Table
        while (rs.next()) {
            table.addCell(String.valueOf(rs.getInt("PersonID")));
            table.addCell(rs.getString("FirstName"));
            table.addCell(rs.getString("DateOfBirth"));
            table.addCell(rs.getString("Gender"));
            table.addCell(rs.getString("Email"));
            table.addCell(rs.getString("PhoneNumber"));
            table.addCell(rs.getString("City"));
            table.addCell(rs.getString("ROLE"));
        }

        // 5. Finalize Document
        document.add(table);
        document.close();
        
        JOptionPane.showMessageDialog(this, "Staff Report '" + filePath + "' generated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        
        // Optional: Automatically open the generated PDF
        if (Desktop.isDesktopSupported()) {
            File pdfFile = new File(filePath);
            if (pdfFile.exists()) {
                Desktop.getDesktop().open(pdfFile);
            }
        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "SQL Exception", JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "PDF Generation Error: " + ex.getMessage(), "iText Exception", JOptionPane.ERROR_MESSAGE);
    } finally {
        if (document.isOpen()) document.close();
        try {
            if (rs != null) rs.close();
            if (pstmt != null) pstmt.close();
            if (conn != null) conn.close();
        } catch (SQLException ex) {
            System.err.println("Error closing resources: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    Document document = new Document();
    String filePath = "StaffReport.pdf"; // Output file name

    // SQL to fetch Staff data: Filtering by ROLE
    String sql = "SELECT PersonID, FirstName, DateOfBirth, Gender, Email, PhoneNumber, City, ROLE "
               + "FROM persons WHERE ROLE IN ('STUDENT') ORDER BY PersonID";

    try {
        // 1. Database Connection
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel_management_system","root", "");
        pstmt = conn.prepareStatement(sql);
        rs = pstmt.executeQuery();

        // 2. iText Setup
        PdfWriter.getInstance(document, new FileOutputStream(filePath));
        document.open();

        // 3. Add Title and Header (8 columns)
         Paragraph title = new Paragraph("MILE 6 HOSTEL");
        title.setAlignment(Element.ALIGN_CENTER);
        title.setSpacingAfter(20);
        title.setFont(new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 16, com.itextpdf.text.Font.BOLD));
        document.add(title);
        document.add(new Paragraph("\n\nRegistered Students Report\n\n", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18)));
        PdfPTable table = new PdfPTable(8); 
        table.setWidthPercentage(100);
        
        // Headers
        table.addCell("ID"); table.addCell("Name"); table.addCell("DOB");
        table.addCell("Gender"); table.addCell("Email"); table.addCell("Phone");
        table.addCell("City"); table.addCell("Role");

        // 4. Populate Table
        while (rs.next()) {
            table.addCell(String.valueOf(rs.getInt("PersonID")));
            table.addCell(rs.getString("FirstName"));
            table.addCell(rs.getString("DateOfBirth"));
            table.addCell(rs.getString("Gender"));
            table.addCell(rs.getString("Email"));
            table.addCell(rs.getString("PhoneNumber"));
            table.addCell(rs.getString("City"));
            table.addCell(rs.getString("ROLE"));
        }

        // 5. Finalize Document
        document.add(table);
        document.close();
        
        JOptionPane.showMessageDialog(this, "Staff Report '" + filePath + "' generated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        
        // Optional: Automatically open the generated PDF
        if (Desktop.isDesktopSupported()) {
            File pdfFile = new File(filePath);
            if (pdfFile.exists()) {
                Desktop.getDesktop().open(pdfFile);
            }
        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "SQL Exception", JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "PDF Generation Error: " + ex.getMessage(), "iText Exception", JOptionPane.ERROR_MESSAGE);
    } finally {
        if (document.isOpen()) document.close();
        try {
            if (rs != null) rs.close();
            if (pstmt != null) pstmt.close();
            if (conn != null) conn.close();
        } catch (SQLException ex) {
            System.err.println("Error closing resources: " + ex.getMessage());
        }
    }

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddStaff;
    private javax.swing.JButton AddStudent;
    private javax.swing.JMenuItem complaintsMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDepartmentID;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblRegID;
    private javax.swing.JLabel lblRegID1;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStdname;
    private javax.swing.JLabel lblStfpassword;
    private javax.swing.JLabel lblcourse;
    private javax.swing.JLabel lbldateofhire;
    private javax.swing.JLabel lblemergencyContact;
    private javax.swing.JLabel lblemergencyName;
    private javax.swing.JLabel lblemergencyRelation;
    private javax.swing.JLabel lblstdpassword;
    private javax.swing.JLabel lblstfName;
    private javax.swing.JLabel lblyear;
    private javax.swing.JPanel staffPanel;
    private javax.swing.JComboBox<String> statusBox;
    private javax.swing.JPanel studentPanel;
    private com.toedter.calendar.JDateChooser txtDateOfEnrollment;
    private javax.swing.JTextField txtDepartmentID;
    private javax.swing.JTextField txtRole;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtStfName;
    private javax.swing.JTextField txtStfpassword;
    private javax.swing.JTextField txtcourse;
    private com.toedter.calendar.JDateChooser txtdateofhire;
    private javax.swing.JTextField txtemergencyContact;
    private javax.swing.JTextField txtemergencyName;
    private javax.swing.JTextField txtemergencyRelation;
    private javax.swing.JTextField txtemployeeID;
    private javax.swing.JTextField txtstdName;
    private javax.swing.JTextField txtstdRegID;
    private javax.swing.JTextField txtstdpassword;
    private javax.swing.JTextField txtstfRegID;
    // End of variables declaration//GEN-END:variables
}
