/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat; // For formatting dates
import java.sql.DriverManager;    // For database connection
import java.sql.Date;
import javax.swing.JOptionPane;
// For database connection
// You will also need your database connection utility imports
// import java.sql.DriverManager;
/**
 *
 * @author HP
 */
public class AssignRoom extends javax.swing.JFrame {

    /**
     * Creates new form AssignRoom
     */
    public AssignRoom() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtStdID = new javax.swing.JTextField();
        txtRoomID = new javax.swing.JTextField();
        txtTerm = new javax.swing.JComboBox<>();
        checkIn = new com.toedter.calendar.JDateChooser();
        checkOut = new com.toedter.calendar.JDateChooser();
        txtAmount = new javax.swing.JTextField();
        btnAssign = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 255));

        jLabel1.setText("ROOM ASSIGNMENT");

        jLabel2.setText("STUDENT ID");

        jLabel3.setText("ROOM ID");

        jLabel4.setText("TERM ");

        jLabel5.setText("CHECK IN");

        jLabel6.setText("AMOUNT ");

        jLabel7.setText("CHECK OUT");

        txtStdID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStdIDActionPerformed(evt);
            }
        });

        txtTerm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1", "2" }));

        checkIn.setDateFormatString("yyyy-MMdd");

        checkOut.setDateFormatString("yyyy-MM-dd");

        btnAssign.setText("ASSIGN");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAssign)
                .addGap(94, 94, 94))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(118, 118, 118)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStdID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(checkIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(checkOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtStdID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(checkIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(checkOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssign)
                    .addComponent(btnback))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStdIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStdIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStdIDActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
     // --- 1. GET VALUES FROM COMPONENTS ---
    String studentIdStr = txtStdID.getText();
    String roomIdStr = txtRoomID.getText();
    
    // Get TermID from JComboBox
    String termIdStr = txtTerm.getSelectedItem() != null 
                        ? txtTerm.getSelectedItem().toString() 
                        : "";
                        
    // CORRECT DATE RETRIEVAL: Get java.util.Date from the picker and cast explicitly
    java.util.Date checkInUtilDate = (java.util.Date) checkIn.getDate(); 
    java.util.Date checkOutUtilDate = (java.util.Date) checkOut.getDate(); 

    // Create the formatter for the required SQL format: YYYY-MM-DD
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

    // Format dates to String. This will be an empty string if no date was selected (null)
    String checkInDateStr = (checkInUtilDate != null) 
                            ? dateFormat.format(checkInUtilDate) 
                            : "";
    String checkOutDateStr = (checkOutUtilDate != null) 
                            ? dateFormat.format(checkOutUtilDate) 
                            : "";
                             
    String rentAmountStr = txtAmount.getText();
    
    // --- 2. INITIAL VALIDATION (Check for empty fields) ---
    if (studentIdStr.isEmpty() || roomIdStr.isEmpty() || termIdStr.isEmpty() || 
        checkInDateStr.isEmpty() || checkOutDateStr.isEmpty() || rentAmountStr.isEmpty()) {
        
        JOptionPane.showMessageDialog(this, "Please ensure all assignment fields are selected/entered.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return; 
    }
    
    // Variables for type conversion
    int studentID, roomID, termID;
    double rentAmount;

    // --- 3. TYPE CONVERSION AND VALIDATION (IDs and Amount) ---
    try {
        studentID = Integer.parseInt(studentIdStr);
        roomID = Integer.parseInt(roomIdStr);
        termID = Integer.parseInt(termIdStr);
        rentAmount = Double.parseDouble(rentAmountStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Student ID, Room ID, Term ID, and Amount must be valid numbers.", "Data Type Error", JOptionPane.ERROR_MESSAGE);
        return; 
    }

    // --- 4. DATABASE LOGIC (INSERT) ---
    Connection con = null;
    PreparedStatement ps = null;

    try {
        // Database connection setup
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel_management_system", "root", "mark24"); 
        
        // SQL query: Omit AssignmentID as it's an Auto-Increment (AI PK)
        String query = "INSERT INTO roomassignments " + 
                       "(StudentID, RoomID, TermID, CheckInDate, CheckOutDate, RentAmount) " + 
                       "VALUES (?, ?, ?, ?, ?, ?)";
        ps = con.prepareStatement(query);
        
        // Bind the 6 parameters
       // Convert Formatted Strings to java.sql.Date objects
    java.sql.Date checkInDate = java.sql.Date.valueOf(checkInDateStr);
        java.sql.Date checkOutDate = java.sql.Date.valueOf(checkOutDateStr);

        // Bind parameters
        ps.setInt(1, studentID);
        ps.setInt(2, roomID);
        ps.setInt(3, termID);
        ps.setDate(4, checkInDate);
        ps.setDate(5, checkOutDate);
        ps.setDouble(6, rentAmount);

        // Execute the update
        int rowsInserted = ps.executeUpdate();

        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Room successfully assigned!", "Success", JOptionPane.INFORMATION_MESSAGE);
            // Optionally clear fields after success
            // clearFormFields(); 
        }

    } catch (SQLException ex) {
        // Catches database-specific errors (e.g., Foreign Key violation if IDs don't exist)
        String errorMsg = "Database Error: " + ex.getMessage() + ". Check if Student ID, Room ID, or Term ID are valid and exist in the master tables.";
        JOptionPane.showMessageDialog(this, errorMsg, "SQL Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    } catch (IllegalArgumentException ex) {
        // Catches errors related to date parsing (shouldn't happen with the current logic, but good safeguard)
        JOptionPane.showMessageDialog(this, "Internal Date Format Error.", "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    } catch (Exception ex) {
        // Handle other general exceptions (e.g., connection failure)
        JOptionPane.showMessageDialog(this, "An unexpected error occurred: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } finally {
        // Close resources
        try { if (ps != null) ps.close(); } catch (SQLException e) { e.printStackTrace(); }
        try { if (con != null) con.close(); } catch (SQLException e) { e.printStackTrace(); }
    }
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnback;
    private com.toedter.calendar.JDateChooser checkIn;
    private com.toedter.calendar.JDateChooser checkOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtRoomID;
    private javax.swing.JTextField txtStdID;
    private javax.swing.JComboBox<String> txtTerm;
    // End of variables declaration//GEN-END:variables
}
