import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date; // For working with date components like JDateChooser
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp; // Required for java.sql.Timestamp
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class Staff extends javax.swing.JFrame {

    /**
     * Creates new form Staff
     */
    public Staff() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtenterid = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        btnEnter = new javax.swing.JButton();
        BtnStfBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtStfname = new javax.swing.JTextField();
        txtEmployeeID = new javax.swing.JTextField();
        txtdepartment = new javax.swing.JTextField();
        txtjob = new javax.swing.JTextField();
        txtdateofhire = new javax.swing.JTextField();
        txtstatus = new javax.swing.JTextField();
        txtsalary = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComplaint = new javax.swing.JTextArea();
        btncomplaint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ENTER ID");

        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("PASSWORD");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("STAFF PORTAL");

        btnEnter.setText("VIEW DETAILS");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        BtnStfBack.setText("BACK");
        BtnStfBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStfBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEnter)
                            .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassword)
                            .addComponent(txtenterid, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnStfBack)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 5, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtenterid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnter)
                .addGap(29, 29, 29)
                .addComponent(BtnStfBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAME");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EMPLOYEE ID");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DEPARTMENT");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("JOB TITLE");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DATE OF HIRE");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("STATUS");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SALARY");

        txtStfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStfnameActionPerformed(evt);
            }
        });

        txtdateofhire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateofhireActionPerformed(evt);
            }
        });

        txtComplaint.setColumns(20);
        txtComplaint.setRows(5);
        txtComplaint.setText("ADD COMPLAINT (OPTIONAL)");
        jScrollPane1.setViewportView(txtComplaint);

        btncomplaint.setText("SUBMIT COMPLAINT");
        btncomplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomplaintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtStfname, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(txtEmployeeID)
                            .addComponent(txtdepartment)
                            .addComponent(txtjob)
                            .addComponent(txtdateofhire)
                            .addComponent(txtstatus)
                            .addComponent(txtsalary)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btncomplaint)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txtdepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtjob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtdateofhire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btncomplaint)))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnStfBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStfBackActionPerformed
        Menu.Main();
        this.dispose();
    }//GEN-LAST:event_BtnStfBackActionPerformed

    private void txtStfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStfnameActionPerformed

    private void txtdateofhireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateofhireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateofhireActionPerformed
    private void clearDetailFields() {
    txtStfname.setText("");
    txtEmployeeID.setText("");
    txtdepartment.setText("");
    txtjob.setText("");
    txtdateofhire.setText("");
    txtstatus.setText("");
    txtsalary.setText("");
}
    
    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
    // 1. Get input from the login fields
    String enteredID = txtenterid.getText().trim();
    // Assuming the password field uses getPassword() and we convert it to a String for comparison
    String enteredPassword = txtpassword.getText().trim(); 
    
    // Clear the detail fields first in case of a failed lookup
    clearDetailFields(); 
    
    // 2. SQL query to find the staff member
    // We check against the EmployeeID and password columns.
    // Assuming 'enteredID' is the EmployeeID
    String sql = "SELECT StaffID, Fullname, EmployeeID, JobTitle, DateOfHire, EmploymentStatus, Salary, DepartmentID "
               + "FROM staff WHERE StaffID = ? AND password = ?";
     int staffid = Integer.parseInt(enteredID);
    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel_management_system", "root", "mark24"); 
        try ( // Assume 'conn' is your active database Connection object
            PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setInt(1, staffid);
            pstmt.setString(2, enteredPassword);
            
            // 3. Process the result set
            try (ResultSet rs = pstmt.executeQuery()) {
                // 3. Process the result set
                if (rs.next()) {
                    // Staff member found: Populate the detail fields
                    
                    // Get data from the result set
                    String fullName = rs.getString("Fullname");
                    String employeeID = rs.getString("EmployeeID");
                    String jobTitle = rs.getString("JobTitle");
                    java.sql.Date dateOfHire = rs.getDate("DateOfHire");
                    String status = rs.getString("EmploymentStatus");
                    double salary = rs.getDouble("Salary");
                    int departmentID = rs.getInt("DepartmentID"); // Using DepartmentID from table
                    
                    // Set data to the form fields
                    txtStfname.setText(fullName);
                    txtEmployeeID.setText(employeeID);
                    txtjob.setText(jobTitle);
                    
                    // Format the date for display
                    txtdateofhire.setText(dateOfHire != null ? dateOfHire.toString() : "");
                    
                    txtstatus.setText(status);
                    txtsalary.setText(String.format("%.2f", salary));
                    
                    // For Department, you might need an extra lookup to convert DepartmentID to Name
                    txtdepartment.setText(String.valueOf(departmentID));
                    
                    JOptionPane.showMessageDialog(this, "Staff details loaded successfully.");
                } else {
                    // No matching record found
                    JOptionPane.showMessageDialog(this, "Invalid ID or Password. Access Denied.", "Login Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
    
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btncomplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomplaintActionPerformed
       // 1. Get data from form and previously retrieved data
    
    // Retrieve the StaffID from the field used for the initial login (txtEnterID)
    // IMPORTANT: Ensure this field contains a valid StaffID from the earlier "VIEW DETAILS" lookup.
    int assignedStaffID;
    try {
        assignedStaffID = Integer.parseInt(txtenterid.getText().trim());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Error: Staff ID is missing or invalid. Please view details first.", "Submission Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Get the complaint text from the JTextArea
    String description = txtComplaint.getText().trim();
    
    if (description.isEmpty()) {
        JOptionPane.showMessageDialog(this, "The complaint description cannot be empty.", "Submission Error", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // 2. Auto-generate the submission date
    // Use java.sql.Timestamp for the 'datetime' type in the database.
    Timestamp submitDate = new Timestamp(System.currentTimeMillis());

    // 3. Prepare the SQL INSERT statement
    // ComplaintID is auto-incremented, so we don't include it.
    String sql = "INSERT INTO complaints (AssignedStaffID, SubmitDate, Description) VALUES (?, ?, ?)";

    try {
        // Assume 'conn' is your active database Connection object
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel_management_system", "root", "mark24"); 
        PreparedStatement pstmt = conn.prepareStatement(sql);
        
        pstmt.setInt(1, assignedStaffID);     // Staff ID retrieved from the form/session
        pstmt.setTimestamp(2, submitDate);     // Auto-generated timestamp
        pstmt.setString(3, description);       // Complaint text
        
        int rowsInserted = pstmt.executeUpdate();
        
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Complaint submitted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            // Clear the complaint text area after submission
            txtComplaint.setText(""); 
        } else {
             JOptionPane.showMessageDialog(this, "Complaint submission failed.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
        
        pstmt.close();
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Database Error: Could not submit complaint. " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btncomplaintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void staff() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnStfBack;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btncomplaint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextArea txtComplaint;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtStfname;
    private javax.swing.JTextField txtdateofhire;
    private javax.swing.JTextField txtdepartment;
    private javax.swing.JTextField txtenterid;
    private javax.swing.JTextField txtjob;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtsalary;
    private javax.swing.JTextField txtstatus;
    // End of variables declaration//GEN-END:variables
}
