/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date; // Although not strictly necessary if you only use java.sql.Date directly, 
                      // it's good practice if you handle general date objects.
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.io.FileNotFoundException;
import javax.swing.JOptionPane;
import java.awt.Desktop;
import java.io.File;
/**
 *
 * @author HP
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("student portal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblstdID = new javax.swing.JLabel();
        txtStdID = new javax.swing.JTextField();
        lblstdPassword = new javax.swing.JLabel();
        txtstdPassword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        BtnStdBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcourse = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtroomID = new javax.swing.JTextField();
        txtamount = new javax.swing.JTextField();
        txtstatus = new javax.swing.JTextField();
        txtdateofpayment = new javax.swing.JTextField();
        btnPrint = new javax.swing.JButton();

        jLabel3.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STUDENT PORTAL");

        lblstdID.setForeground(new java.awt.Color(255, 255, 255));
        lblstdID.setText("STUDENT ID");

        lblstdPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblstdPassword.setText("PASSWORD");

        jButton1.setText("VIEW DETAILS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BtnStdBack.setText("BACK");
        BtnStdBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStdBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnStdBack)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblstdID)
                        .addComponent(txtStdID)
                        .addComponent(lblstdPassword)
                        .addComponent(txtstdPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblstdID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStdID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblstdPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtstdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addGap(32, 32, 32)
                .addComponent(BtnStdBack)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("COURSE");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NAME");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ROOM ID");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RENT AMOUNT");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("STATUS");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DATE OF PAYMENT");

        txtcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcourseActionPerformed(evt);
            }
        });

        txtstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstatusActionPerformed(evt);
            }
        });

        btnPrint.setText("PRINT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPrint)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(98, 98, 98)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtname)
                            .addComponent(txtcourse)
                            .addComponent(txtroomID)
                            .addComponent(txtamount)
                            .addComponent(txtstatus)
                            .addComponent(txtdateofpayment, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(txtroomID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtdateofpayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtcourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrint)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnStdBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStdBackActionPerformed
        Menu.Main();
        this.dispose();
    }//GEN-LAST:event_BtnStdBackActionPerformed

    private void txtcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcourseActionPerformed

    private void txtstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstatusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      // Clear the detail fields before a new lookup
    
    
    // 1. Get input and validate Student ID
    int studentID = -1;
    String enteredPassword =txtstdPassword.getText().trim(); 
    
    try {
        studentID = Integer.parseInt(txtStdID.getText().trim());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error: The Student ID must be a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return; // Stop execution if ID is not a number
    }

    // 2. SQL query to find the student based on ID and Password
    String studentSql = "SELECT Fullname, CourseOfStudy FROM students WHERE StudentID = ? AND password = ?";
    
    // 3. SQL query to fetch the LAST payment details for the found student
    // NOTE: This assumes 'payments' table is relevant for 'DATE OF PAYMENT'
    String paymentSql = "SELECT Amount, PaymentDate, paymentStatus FROM payments "
                      + "WHERE StudentID = ? ORDER BY PaymentDate DESC LIMIT 1";

    try {
        // Assume 'conn' is your active database Connection object
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel_management_system", "root", "mark24"); 
        // --- A. Lookup Student Details ---
        PreparedStatement studentPstmt = conn.prepareStatement(studentSql);
        studentPstmt.setInt(1, studentID);
        studentPstmt.setString(2, enteredPassword);

        ResultSet studentRs = studentPstmt.executeQuery();

        if (studentRs.next()) {
            // Student found: Populate basic details
            String fullName = studentRs.getString("Fullname");
            String course = studentRs.getString("CourseOfStudy");

            txtname.setText(fullName);
            txtcourse.setText(course);
            
            // NOTE: Room ID, Rent Amount logic is missing and must be added here
            // e.g., txtRoomID.setText(fetchRoomID(studentID));
            // e.g., txtRentAmount.setText(fetchRentAmount(course));

            // --- B. Lookup Last Payment Details ---
            PreparedStatement paymentPstmt = conn.prepareStatement(paymentSql);
            paymentPstmt.setInt(1, studentID);
            ResultSet paymentRs = paymentPstmt.executeQuery();
            
            if (paymentRs.next()) {
                // Payment details found: Populate status and payment date
                String paymentStatus = paymentRs.getString("paymentStatus");
                java.sql.Date paymentDate = paymentRs.getDate("PaymentDate");
                
                txtstatus.setText("Paid: " + paymentStatus); // Using payment status for general status
                txtdateofpayment.setText(paymentDate != null ? paymentDate.toString() : "N/A");
            } else {
                txtstatus.setText("Payment Required"); // Default status if no payment record is found
                txtdateofpayment.setText("No Records");
            }
            
            paymentRs.close();
            paymentPstmt.close();

            JOptionPane.showMessageDialog(this, "Student details loaded successfully.");
            
        } else {
            // No matching student record found
            JOptionPane.showMessageDialog(this, "Invalid Student ID or Password. Access Denied.", "Login Error", JOptionPane.ERROR_MESSAGE);
        }

        studentRs.close();
        studentPstmt.close();

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed
    private void addCellToTable(PdfPTable table, String label, String value, int fontStyle) {
    // Cell for the Label (Key)
    PdfPCell labelCell = new PdfPCell(new Phrase(label, new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 10, com.itextpdf.text.Font.BOLD)));
    labelCell.setBorder(PdfPCell.NO_BORDER);
    table.addCell(labelCell);

    // Cell for the Value
    PdfPCell valueCell = new PdfPCell(new Phrase(value, new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 10, fontStyle)));
    valueCell.setBorder(PdfPCell.NO_BORDER);
    table.addCell(valueCell);
}
    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
    // 1. Get data from the form fields
    String studentID = txtStdID.getText().trim();
    String studentName = txtname.getText();
    String course = txtcourse.getText();
    String roomID = txtroomID.getText();
    String rentAmount = txtamount.getText();
    String status = txtstatus.getText();
    String dateOfPayment = txtdateofpayment.getText();
    
    // Check if details were loaded before printing
    if (studentName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please view student details first before printing.", "Print Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Define the output file path (e.g., to the user's home directory)
    String FILE_NAME = "Hostel_Record_" + studentID + ".pdf";
    String path = System.getProperty("user.home") + File.separator + FILE_NAME;

    Document document = new Document();
    
    try {
        // 2. Initialize PDF Writer
        PdfWriter.getInstance(document, new FileOutputStream(path));
        document.open();

        // 3. Add Title
        Paragraph title = new Paragraph("MILE 6 HOSTEL");
        title.setAlignment(Element.ALIGN_CENTER);
        title.setSpacingAfter(20);
        title.setFont(new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 16, com.itextpdf.text.Font.BOLD));
        document.add(title);

        // Add a line break for separation
        document.add(new Paragraph(new Phrase("--- Student Payment Summary ---")));
        document.add(new Paragraph(" ")); // Blank line

        // 4. Create a table to format the details like a form (2 columns: Label | Value)
        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(80); // Table takes up 80% of page width
        table.setSpacingBefore(10f); 
        table.setSpacingAfter(10f);
        
        // Add Rows (Key-Value pairs)
        addCellToTable(table, "STUDENT ID:", studentID, com.itextpdf.text.Font.BOLD);
        addCellToTable(table, "NAME:", studentName, com.itextpdf.text.Font.NORMAL);
        addCellToTable(table, "COURSE:", course, com.itextpdf.text.Font.NORMAL);
        addCellToTable(table, "ROOM ID:", roomID, com.itextpdf.text.Font.NORMAL);
        addCellToTable(table, "RENT AMOUNT:", rentAmount, com.itextpdf.text.Font.NORMAL);
        addCellToTable(table, "STATUS:", status, com.itextpdf.text.Font.NORMAL);
        addCellToTable(table, "DATE OF PAYMENT:", dateOfPayment, com.itextpdf.text.Font.NORMAL);

        document.add(table);
        
        document.close();
        
        JOptionPane.showMessageDialog(this, "PDF generated successfully at: " + path, "Print Success", JOptionPane.INFORMATION_MESSAGE);
        
        // Optional: Automatically open the PDF file
        if (Desktop.isDesktopSupported()) {
            Desktop.getDesktop().open(new File(path));
        }

    } catch (FileNotFoundException | DocumentException e) {
        JOptionPane.showMessageDialog(this, "Error generating PDF: " + e.getMessage(), "PDF Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "An unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnStdBack;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblstdID;
    private javax.swing.JLabel lblstdPassword;
    private javax.swing.JTextField txtStdID;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtcourse;
    private javax.swing.JTextField txtdateofpayment;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtroomID;
    private javax.swing.JTextField txtstatus;
    private javax.swing.JTextField txtstdPassword;
    // End of variables declaration//GEN-END:variables
}
