/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable; // Import JTable
/**
 *
 * @author HP
 */
public class ViewComplaints extends javax.swing.JFrame {

    /**
     * Creates new form ViewComplaints
     */
    public ViewComplaints() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ComplaintsTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("COMPLAINTS");

        ComplaintsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STAFF ID", "DATE", "COMPLAINT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ComplaintsTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(ComplaintsTable);

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnLoad.setText("LOAD");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLoad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete)
                        .addGap(113, 113, 113)
                        .addComponent(btnBack))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(221, 221, 221)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnLoad)
                    .addComponent(btnDelete))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
      AdminForm.Main();
      this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
       // 1. Get the current table model
    DefaultTableModel model = (DefaultTableModel) ComplaintsTable.getModel();
    
    // Clear any existing data in the table
    model.setRowCount(0); 

    // Define columns based on your table header (STAFF ID, DATE, COMPLAINT)
    // Note: The JTable header might need to be explicitly set in the model if not done in the GUI builder.
    // String[] columnNames = {"STAFF ID", "DATE", "COMPLAINT"}; 
    // model.setColumnIdentifiers(columnNames); 

    // 2. SQL query to select all complaints
    // We select the StaffID, SubmitDate, and Description columns from the 'complaints' table.
    String sql = "SELECT AssignedStaffID, SubmitDate, Description FROM complaints ORDER BY SubmitDate DESC";

    try {
        // Assume 'conn' is your active database Connection object
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel_management_system", "root", ""); 
        PreparedStatement pstmt = conn.prepareStatement(sql);
        ResultSet rs = pstmt.executeQuery();

        // 3. Process the result set and populate the JTable
        while (rs.next()) {
            // Retrieve data for one complaint record
            int staffID = rs.getInt("AssignedStaffID");
            // The database is datetime, so we can get it as a String or format the Timestamp object
            String submitDate = rs.getTimestamp("SubmitDate").toString(); 
            String description = rs.getString("Description");
            
            // Create an array of objects for the JTable row
            Object[] row = {staffID, submitDate, description};
            
            // Add the row to the table model
            model.addRow(row);
        }
        
        JOptionPane.showMessageDialog(this, "Complaints loaded successfully!", "Load Complete", JOptionPane.INFORMATION_MESSAGE);
        
        rs.close();
        pstmt.close();

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Database Error: Could not load complaints. " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       // 1. Show a confirmation dialog
    int dialogResult = JOptionPane.showConfirmDialog(
        this, 
        "Are you sure you want to delete ALL complaint records? This action cannot be undone.", 
        "Confirm Deletion of All Data", 
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE
    );

    // Proceed only if the administrator clicks 'Yes'
    if (dialogResult == JOptionPane.YES_OPTION) {
        
        // Use TRUNCATE TABLE for a faster and cleaner removal of all rows (resets auto-increment IDs)
        // If TRUNCATE is not allowed by your database user permissions, use DELETE FROM.
        // String sql = "DELETE FROM complaints"; 
        String sql = "TRUNCATE TABLE complaints"; 

        try {
            // Assume 'conn' is your active database Connection object
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel_management_system", "root", "mark24");
            PreparedStatement pstmt = conn.prepareStatement(sql);
            
            // For TRUNCATE TABLE, executeUpdate is used, but the return value is often 0
            pstmt.executeUpdate();
            
            // 2. Clear the JTable display after successful database deletion
            DefaultTableModel model = (DefaultTableModel) ComplaintsTable.getModel();
            model.setRowCount(0); 

            JOptionPane.showMessageDialog(this, "All complaint records have been successfully deleted!", "Deletion Complete", JOptionPane.INFORMATION_MESSAGE);

            pstmt.close();

        } catch (SQLException ex) {
            // This is crucial for handling permission issues (like TRUNCATE not allowed)
            JOptionPane.showMessageDialog(this, "Database Error: Could not delete data. Please check user permissions or try DELETE FROM instead of TRUNCATE. Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewComplaints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewComplaints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewComplaints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewComplaints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewComplaints().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ComplaintsTable;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLoad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
